### ISSUE TITLE
Populating the twarc subdirectory

### ISSUE THREAD

**Issue by ice-water** [pbinkley/twarc-report#7]
When I try the second command:
git submodule update
I get:
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:edsu/twarc.git' into submodule path 'twarc' failed

**Comment by pbinkley** [comment]
Sorry about that. I've just pushed a fix - could you pull and try again and let me know if it works for you? The problem was that I specified the submodule with a git url, so it required ssh authentfication on github. I've replaced it with the equivalent https url, so no authentication is needed.

**Comment by ice-water** [comment]
Thank you for the quick response and I apologize for the dryness of my previous message. I pulled and still got the same error message, but it worked after deleting twarc-report and cloning again. Thank you again!

**Comment by spacepirate0001** [comment]
I think you should also include in the instructions that you need to initiate git first:

git init
git submodule init
git submodule update

this would be clearer to follow along I suppose. Thank you for sharing the code...

**Comment by pbinkley** [comment]
Fixed by 8e3ff74
