### ISSUE TITLE
clarification of harvest.py's relationship to twarc submodule

### ISSUE THREAD

**Issue by skilfullycurled** [pbinkley/twarc-report#9]
Hello,

Thank you so much for extending the twarc library!

This isn't an issue in the classic sense so I apologize for using this mechanism.

I was wondering if you could say a bit more about the relationship between harvest.py and twarc (the submodule specified, not the most current version).

More specifically, from looking at the code in harvest.py which eventually calls upon twarc's archive.py, it does not seem that there is a mechanism for including the API keys.  The version of twarc that twarc-report uses called upon one to enter them as:

`twarc.py --consumer_key foo --consumer_secret bar --access_token baz --access_token_secret bez --search ferguson`

How is this handled in when using harvest.py?

Thanks for your help!

Benjamin

**Comment by pbinkley** [comment]
Now uses twarc-archive.py directly 8e3ff74
